# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_card.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(970, 827)
        Dialog.setMinimumSize(QtCore.QSize(970, 827))
        Dialog.setMaximumSize(QtCore.QSize(970, 827))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        Dialog.setFont(font)
        self.pushButton_home = QtWidgets.QPushButton(Dialog)
        self.pushButton_home.setGeometry(QtCore.QRect(30, 40, 150, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.pushButton_home.setFont(font)
        self.pushButton_home.setObjectName("pushButton_home")
        self.pushButton_love = QtWidgets.QPushButton(Dialog)
        self.pushButton_love.setGeometry(QtCore.QRect(30, 140, 150, 80))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.pushButton_love.setFont(font)
        self.pushButton_love.setObjectName("pushButton_love")
        self.pushButton_next = QtWidgets.QPushButton(Dialog)
        self.pushButton_next.setGeometry(QtCore.QRect(30, 280, 150, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_previous = QtWidgets.QPushButton(Dialog)
        self.pushButton_previous.setGeometry(QtCore.QRect(30, 390, 150, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.pushButton_previous.setFont(font)
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.pushButton_close = QtWidgets.QPushButton(Dialog)
        self.pushButton_close.setGeometry(QtCore.QRect(30, 730, 150, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_heart = QtWidgets.QPushButton(Dialog)
        self.pushButton_heart.setGeometry(QtCore.QRect(30, 500, 150, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.pushButton_heart.setFont(font)
        self.pushButton_heart.setObjectName("pushButton_heart")
        self.pushButton_play = QtWidgets.QPushButton(Dialog)
        self.pushButton_play.setGeometry(QtCore.QRect(30, 610, 150, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.pushButton_play.setFont(font)
        self.pushButton_play.setObjectName("pushButton_play")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(249, 29, 661, 751))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.page.setObjectName("page")
        self.label_pix = QtWidgets.QLabel(self.page)
        self.label_pix.setGeometry(QtCore.QRect(70, 10, 491, 521))
        self.label_pix.setText("")
        self.label_pix.setObjectName("label_pix")
        self.label_text = QtWidgets.QLabel(self.page)
        self.label_text.setGeometry(QtCore.QRect(10, 480, 631, 261))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.label_text.setFont(font)
        self.label_text.setText("")
        self.label_text.setObjectName("label_text")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_plot = QtWidgets.QLabel(self.page_2)
        self.label_plot.setGeometry(QtCore.QRect(60, 40, 541, 481))
        self.label_plot.setText("")
        self.label_plot.setObjectName("label_plot")
        self.label_text_2 = QtWidgets.QLabel(self.page_2)
        self.label_text_2.setGeometry(QtCore.QRect(10, 400, 631, 271))
        self.label_text_2.setText("")
        self.label_text_2.setObjectName("label_text_2")
        self.pushButton_click = QtWidgets.QPushButton(self.page_2)
        self.pushButton_click.setGeometry(QtCore.QRect(490, 690, 150, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.pushButton_click.setFont(font)
        self.pushButton_click.setObjectName("pushButton_click")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_play = QtWidgets.QLabel(self.page_3)
        self.label_play.setGeometry(QtCore.QRect(20, 20, 581, 191))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.label_play.setFont(font)
        self.label_play.setObjectName("label_play")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_8.setGeometry(QtCore.QRect(250, 550, 111, 91))
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_1 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_1.setGeometry(QtCore.QRect(90, 230, 111, 91))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(28)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setMouseTracking(False)
        self.pushButton_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_1.setText("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 390, 111, 91))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_7.setGeometry(QtCore.QRect(90, 550, 111, 91))
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_start = QtWidgets.QPushButton(self.page_3)
        self.pushButton_start.setGeometry(QtCore.QRect(500, 690, 150, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 230, 111, 91))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 390, 111, 91))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_6.setGeometry(QtCore.QRect(410, 390, 111, 91))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 230, 111, 91))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_9.setGeometry(QtCore.QRect(410, 550, 111, 91))
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.stackedWidget.addWidget(self.page_3)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "LoveU"))
        self.pushButton_home.setText(_translate("Dialog", "Home"))
        self.pushButton_love.setText(_translate("Dialog", "Love\n"
"Start"))
        self.pushButton_next.setText(_translate("Dialog", "Next"))
        self.pushButton_previous.setText(_translate("Dialog", "Previous"))
        self.pushButton_close.setText(_translate("Dialog", "Close"))
        self.pushButton_heart.setText(_translate("Dialog", "Heart"))
        self.pushButton_play.setText(_translate("Dialog", "Play"))
        self.pushButton_click.setText(_translate("Dialog", "Click"))
        self.label_play.setText(_translate("Dialog", "遊戲說明:"))
        self.pushButton_start.setText(_translate("Dialog", "Start"))
